/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Flamez Docs",
  "tagline": "Ignite your future",
  "url": "https://flamez.io",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "trailingSlash": false,
  "organizationName": "Butane",
  "projectName": "Docs",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "customFields": {
    "project": {
      "name": "Flamez",
      "denom": "FLMZ",
      "ticker": "$BBC",
      "binary": "bbcsd",
      "testnet_denom": "tBBC",
      "testnet_ticker": "tBBC",
      "chain_id": "535037",
      "testnet_chain_id": "892272",
      "latest_version": "v11.0.1",
      "mainnet_version": "v11.0.1",
      "testnet_version": "v11.0.1",
      "version_number": "2",
      "testnet_version_number": "4",
      "testnet_evm_explorer_url": "https://testnet.bbcscan.io/",
      "evm_explorer_url": "https://bbcscan.io/",
      "testnet_butane_explorer_url": "https://testnet.bbcscan.io/",
      "butane_explorer_url": "https://bbcscan.io/"
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "docs/home",
          "sidebarPath": "C:\\Users\\doubl\\The_AME_docs\\Flamez_Docs\\sidebars.js",
          "breadcrumbs": true
        },
        "blog": false,
        "theme": {
          "customCss": "C:\\Users\\doubl\\The_AME_docs\\Flamez_Docs\\src\\css\\custom.css"
        },
        "gtag": {
          "trackingID": "G-3JSJBBPS3L",
          "anonymizeIP": false
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "docs/use",
        "routeBasePath": "use",
        "id": "use",
        "sidebarPath": "C:\\Users\\doubl\\The_AME_docs\\Flamez_Docs\\sidebars.js",
        "breadcrumbs": true,
        "editUrl": "https://github.com/BUTANE-Smart-Chain/flamezio-frontend"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "docs/develop",
        "routeBasePath": "develop",
        "id": "develop",
        "sidebarPath": "C:\\Users\\doubl\\The_AME_docs\\Flamez_Docs\\sidebars.js",
        "breadcrumbs": true,
        "editUrl": "https://github.com/BUTANE-Smart-Chain/flamezio-frontend"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "docs/validate",
        "routeBasePath": "validate",
        "id": "validate",
        "sidebarPath": "C:\\Users\\doubl\\The_AME_docs\\Flamez_Docs\\sidebars.js",
        "breadcrumbs": true,
        "editUrl": "https://github.com/BUTANE-Smart-Chain/flamezio-frontend"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "docs/protocol",
        "routeBasePath": "protocol",
        "id": "protocol",
        "sidebarPath": "C:\\Users\\doubl\\The_AME_docs\\Flamez_Docs\\sidebars.js",
        "breadcrumbs": true,
        "editUrl": "https://github.com/BUTANE-Smart-Chain/flamezio-frontend"
      }
    ],
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 80,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ],
    null
  ],
  "themeConfig": {
    "navbar": {
      "title": "Flamez Docs",
      "logo": {
        "href": "/",
        "alt": "Flamez Logo",
        "src": "img/Flamezicon.png"
      },
      "items": [
        {
          "position": "left",
          "label": "Use",
          "to": "/use"
        },
        {
          "position": "left",
          "label": "Developers",
          "to": "/protocol"
        },
        {
          "position": "right",
          "label": "Tools",
          "to": "/develop"
        },
        {
          "position": "right",
          "label": "AMM/DEX",
          "to": "https://flamez.io/"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Trade on Flamez",
              "to": "/develop/smart-contracts"
            },
            {
              "label": "Flamez Trending",
              "to": "/use"
            },
            {
              "label": "Stake BBC",
              "to": "https://flamez.io",
              "external": true
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Telegram",
              "href": "https://t.me/butanechain"
            },
            {
              "label": "Youtbe Academy",
              "href": "https://www.youtube.com/@ButaneAcademy"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/zk4t92b9MX"
            },
            {
              "label": "Discord Developers",
              "href": "https://discord.gg/je3pBf2h"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/Butane_Network"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Staking",
              "to": "https://medium.com/@butanegas101"
            },
            {
              "label": "Partner with Flamez",
              "href": "https://github.com/BUTANE-Smart-Chain"
            }
          ]
        }
      ],
      "copyright": " 🔥 Flames Ignition Core Development Team. © 2023 All rights reserved."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "metadata": [
      {
        "name": "Butane Docs",
        "content": "Official Butane Docs. Come discover why we are the the home for native, cross-chain applications."
      },
      {
        "name": "author",
        "content": "The Butane Core Team @ButaneOrg"
      },
      {
        "name": "keywords",
        "content": "EMM, cross-chain, Butane SDK, IBC, fast-finality, native, cross-chain applications, EVM on Butane"
      },
      {
        "name": "viewport",
        "content": "width=device-width, initial-scale=1.0"
      }
    ],
    "algolia": {
      "appId": "DPTADG0ME1",
      "apiKey": "fbbcf85b58f500e5e4d301f9730f3526",
      "indexName": "Butanedocs",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
